[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed.git" }
anyhow = "1"
log = "0.4"
serde = "1.0.203"
serde_json = "1"
wry = "0"
smallvec = "1.13.2"
windows = "0.57.0"
unicode-segmentation = "1.11.0"
schemars = "0.7.0"
util.workspace = true
parking_lot = "0.12.1"

[lints]
workspace = true
